version: "2"
services:
  haproxy:
    image: ${REGISTRY_IP}:5000/haproxy_server
    environment:
      - "consul=${CONSUL_IP}"
      - "constraint:host==nginx"
    networks:
      - app
    extra_hosts:
     - "consul:${CONSUL_IP}"

  nginx:
    image: nginx:latest
    environment:
      - "constraint:host==nginx"
    ports:
        - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - haproxy
    networks:
      - app
    depends_on:
      - haproxy

  mysql:
    image: mariadb
    environment:
      - "constraint:host==mysql"
      - "SERVICE_NAME=mysql"
      - "SERVICE_TAGS=mariadb"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=root"
    ports:
      - 3306:3306
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8181:80
    environment:
      - "constraint:host==mysql"
      - "MYSQL_USERNAME=root"
      - "MYSQL_ROOT_PASSWORD=root"
      - "PMA_HOST=mysql"
    networks:
      - app

  php:
    image: ${REGISTRY_IP}:5000/php_fpm_app
    environment:
      - "constraint:host==app-server"
      - "SERVICE_NAME=app"
      - "SERVICE_TAGS=php"
    ports:
      - "9000:9000"
    networks:
      - app

networks:
  app:
