version: "2"
services:
    consul:
        command: -server -bootstrap
        image: progrium/consul
        ports:
            - "8500:8500"

    registrator:
        command: -internal consul://consul:8500
        image: gliderlabs/registrator:latest
        links:
            - consul
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock"

    haproxy:
        build: ./haproxy
        links:
            - consul

    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - haproxy

    php:
        image: php:7-fpm
        environment:
            - SERVICE_NAME=app
            - SERVICE_TAGS=php
        volumes:
            - ./app:/src
